$ErrorActionPreference = "Stop"

$base = Split-Path -Parent $MyInvocation.MyCommand.Path
$order = @(
    "tool-config.js",
    "tool-utils.js",
    "registry.js",
    "ocr.js",
    "morse.js",
    "semaphore.js",
    "rail-fence.js",
    "bacon.js",
    "rot13.js",
    "a1z26.js",
    "radix-converter.js",
    "binary-text.js",
    "shift.js",
    "custom-table.js",
    "main.js"
)

$outFile = Join-Path $base "bundle.js"
$parts = @("/* text tools bundle: generated by build-bundle.ps1 */")

foreach ($name in $order) {
    $parts += "`n/* ===== source: $name ===== */"
    $parts += Get-Content -LiteralPath (Join-Path $base $name) -Raw -Encoding utf8
}

Set-Content -LiteralPath $outFile -Value ($parts -join "`n") -Encoding utf8
Write-Output "Bundle updated: $outFile"
